version: '3'

volumes:
  cbio-initdb:
    driver: local
  mysql_data:
    driver: local

networks:
  cbio-net:

services:
  cbio-initdb:
    container_name: cbio-initdb
    image: busybox
    command: /bin/ash -c "
               if [ ! -f /root/initdb/00_cgds.sql ]; then
                 wget --no-check-certificate -O /root/initdb/00_cgds.sql https://raw.githubusercontent.com/cBioPortal/cbioportal/v1.18.1/db-scripts/src/main/resources/cgds.sql;
               fi &&
               if [ ! -f /root/initdb/01_seed-cbioportal_hg19_v2.7.3.sql.gz ]; then
                 wget --no-check-certificate -O /root/initdb/01_seed-cbioportal_hg19_v2.7.3.sql.gz https://github.com/cBioPortal/datahub/raw/master/seedDB/seed-cbioportal_hg19_v2.7.3.sql.gz;
               fi"
    volumes:
      - "cbio-initdb:/root/initdb"
    networks:
      - cbio-net
    
  cbio-DB:
    container_name: cbio-DB
    image: mysql:5
    command: --explicit_defaults_for_timestamp=1
    volumes:
      - "mysql_data:/var/lib/mysql"
      - "cbio-initdb:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_DATABASE: cbioportal
      MYSQL_ROOT_PASSWORD: genome123
      MYSQL_USER: cbio_user
      MYSQL_PASSWORD: cbio123
      TZ: "Asia/Tokyo"
    ports:
      - "3306:3306"
    depends_on:
      - "cbio-initdb"
    restart: always
    networks:
      - cbio-net

  cbioportal:
    container_name: cbioportal
    build:
      context: .
      dockerfile: Dockerfile
      args:
        buildno: 1
    image: cbioportal
    volumes:
      - "./data:/root/data"
    environment:
      TZ: "Asia/Tokyo"
    links:
      - "cbio-DB"
    ports:
      - "80:8080"
    depends_on:
      - "cbio-initdb"
      - "cbio-DB"
    restart: always
    networks:
      - cbio-net

  session-service:
    container_name: session-service
    build:
      context: ./session-service
      dockerfile: Dockerfile
      args:
        buildno: 1
    ports:
      - "8090:8080"
    environment:
      - JAVA_OPTS=-Dspring.data.mongodb.uri=mongodb://session-DB:27017/session-service
      # with user/pass enabled:
      # - JAVA_OPTS=-Dspring.data.mongodb.uri=mongodb://sesssion-DB:27017/session-service -Dsecurity.basic.enabled=true -Dsecurity.user.name=user -Dsecurity.user.password=pass
    links:
      - session-DB 
    depends_on:
      - session-DB
    networks:
      - cbio-net

  session-DB:
    container_name: session-DB
    image: mongo:3.6.6
    restart: always
    # this makes mongo use smaller default size limits:
    # https://docs.mongodb.com/manual/reference/program/mongod/#cmdoption-mongod-smallfiles
    command: --smallfiles
    # uncomment this to expose the db port on localhost
    # ports:
    #   - "27017:27017"
    networks:
      - cbio-net
